[project]
name = "noman-cli"
version = "0.1.0"
dependencies = [
    "mistune>=3.1.3",
    "pygments>=2.19.1",
]

[project.scripts]
noman = "noman_cli:viewer.main"

[tool.hatch.build.targets.wheel]
package = ["src/*"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

